---
# tasks file for my-common-packages
# TODO one potential way to do this cleaner is to add a set fact to create the list
- name: install packages in common_packages using pacman
  become: yes
  package:
    name: '{{ item.pacman }}'
    state: present
  loop: '{{ common_packages }}'
  when: ansible_facts['os_family'] == 'Archlinux'

- name: install packages in common_packages using aptitude
  become: yes
  apt:
    name: '{{ item.apt }}'
    state: present
  loop: '{{ common_packages }}'
  when: ansible_facts['os_family'] == 'Debian'
